server:
  port: 0
  #8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
# Custom Property for Image Upload Directory
file:
  upload-dir: uploads/images/


eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: true
#    fetch-registry: true
