server:
  port: 0
# 8081

spring:
  data:
    mongodb:
      uri: mongodb://user:MqL4XeiDb8GhdXGZFVsw8-_mMnfdCzRR9LnShEGkfBkuJFJz@c4d816af-49ef-4b00-9c20-6c9d29cefa27.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
#data:
#    mongodb:
#      uri: mongodb://localhost:27017/eca_user_db

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: true
#    fetch-registry: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
