server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://root:WjrmyZJfWsvZgpIPvXp-BH73W3TqtarraDtcwgU2YLCLsBHZ@14df0079-7253-4681-98d3-eb428c4a9915.asia-southeast1.firestore.goog:443/db-user?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
#data:
#    mongodb:
#      uri: mongodb://localhost:27017/eca_user_db

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: true
#    fetch-registry: true